spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.74.142:3306/com_serpplus_aliservice?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
  data:
    mongodb:
      host: 192.168.74.142
      port: 27017
      database: mlwg
      user: mlwg
      password: mlwg123
  redis:
    host: 192.168.74.142
    password:
    port: 6379
  kafka:
    bootstrap-servers: 192.168.74.142:9092
server:
  port: 8076
eureka:
  client:
    service-url:
      defaultZone: http://192.168.74.142:8761/eureka/

# mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
    # 逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0


rdsLDParams:
  rdsChunk: 50
  mongoDBChunk: 1000
  mongoDBSaleCollection: rdsSale
  mongoDBRefundCollection: rdsRefund
  mongoDBExchangeCollection: tmExchange
  mongoDBExchangeRe: exchangeResults
remote:
  aliAgentUrl: http://localhost:8888